### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by gregoriopellegrino** [edoburu/django-private-storage#6]
Hi,
when I make

`python manage.py migrate`

I get

`ImportError: No module named 'apps'`

How can I fix it?

Thanks,
Gregorio

**Comment by sacredSatan** [comment]
Hey @gregoriopellegrino 

It is because you're not using the correct path to the function defined in: https://github.com/edoburu/django-private-storage/blob/master/private_storage/permissions.py

It is a mistake in the README, 

instead of:
`PRIVATE_STORAGE_AUTH_FUNCTION = 'apps.utils.private_storage.permissions.allow_staff'
`
it should be:
`PRIVATE_STORAGE_AUTH_FUNCTION = 'private_storage.permissions.allow_staff'
`

Hope it helps, I've also created a pull request for the fix.

**Comment by gregoriopellegrino** [comment]
Solved, thanks.
